version: '2'

services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - ./web:/colab

 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   depends_on:
     - web
