version: '2'

services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - ./web:/colab
   depends_on:
     - redis

 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   depends_on:
     - web

 redis:
   restart: always
   image: redis